[project]
name = "fungible-token"
description = "An implementation of SIP010-compliant fungible token in Clarity."
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[contracts.fungible-token]
path = "contracts/fungible-token.clar"
clarity_version = 1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
