[project]
name = "hello-world"
description = "A beginner smart contract with examples of commonly used Clarity expressions and data structures"
authors = []
telemetry = true
cache_dir = './.cache'


[contracts.hello-world]
path = "contracts/hello-world.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
