[project]
name = "lightning-swaps"
description = "Demonstrates LNSwap's submarine swaps between Stacks and Bitcoin"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.stxswap_v10]
path = "contracts/stxswap_v10.clar"
clarity_version = 1

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
