[project]
name = "non-fungible-token-real"
authors = []
description = "An implementation of SIP009-compliant non-fungible tokens in Clarity."
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.non-fungible-token]
path = "contracts/non-fungible-token.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
