[project]
name = "non-fungible-token"
authors = []
description = "Demonstrates a basic NFT collection that conforms to the SIP-009 NFT standard"
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[contracts.non-fungible-token]
path = "contracts/non-fungible-token.clar"

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
