[project]
name = "nft-marketplace"
description = "Demonstartes a minimalistic NFT marketplace that allows users to list NFT for sale"
authors = []
telemetry = true
cache_dir = "./.cache"

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"
[[project.requirements]]
contract_id = "SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard"

[contracts.nft-marketplace]
path = "contracts/nft-marketplace.clar"
clarity_version = 1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
