[project]
name = "non-fungible-token-real"
authors = []
description = ""
telemetry = true
boot_contracts = ["pox", "costs-v2", "bns"]

[[project.requirements]]
contract_id = "SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait"

[project.cache_location]
path = ".requirements"
[contracts.non-fungible-token]
path = "contracts/non-fungible-token.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
